// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/korcen": {
            "post": {
                "description": "Processes a Korcen request and returns the result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "korcen"
                ],
                "summary": "Process Korcen Request",
                "parameters": [
                    {
                        "description": "Korcen Input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/check.Header"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Korcen Result",
                        "schema": {
                            "$ref": "#/definitions/check.Respond"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "check.Header": {
            "type": "object",
            "properties": {
                "input": {
                    "type": "string"
                },
                "replace-end": {
                    "type": "string"
                },
                "replace-front": {
                    "type": "string"
                }
            }
        },
        "check.Respond": {
            "type": "object",
            "properties": {
                "detect": {
                    "type": "boolean"
                },
                "input": {
                    "type": "string"
                },
                "output": {
                    "type": "string"
                },
                "swear": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
