name: Go with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.0'

    - name: Build Go project
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...

    # Docker steps
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t korcen-api .

    - name: Run Docker container
      run: |
        docker run -d -p 7777:7777 korcen-api

    - name: Check Docker container status
      run: |
        docker ps

    - name: Test Docker container
      run: |
        # Wait until the service inside the container is ready
        until curl --silent --fail http://localhost:7777; do
          echo "Waiting for the service to be ready..."
          sleep 5
        done

    - name: Stop Docker container
      run: |
        docker ps -q --filter "ancestor=korcen-api" | xargs -I {} docker stop {}
